### ISSUE TITLE
nested rules miss final semicolon

### ISSUE THREAD

**Issue by stefan-kern** [jonathantneal/postcss-nesting#20]
after this plugins' transformation

```
.a {
  &.b {
    display: block;
    color: #111;
  }
}
```

becomes 

```
.a.b {
  display: block;
  color: #111
}
```

the last semicolon gets lost.

**Comment by tbremer** [comment]
The last semicolon isn't necessary to be valid.

**Comment by stefan-kern** [comment]
You are right it isn't necessary. But i think it isn't this packages' job to deal with semicolons. This effect is unexpected and it could cause issues down the line with other postcss modules. If dropping final semicolons is the desired effect it should be the task of a seperate module.

**Comment by jonathantneal** [comment]
@stefan-kern, I strip all the `raws` from nodes that I work with, because otherwise the spacing will be awkward when you realize your nested declarations have an extra space or tab. Instead, I do this:

```js
node.raws = {};
```

This causes the default behavior in PostCSS to kick in, which is to omit the final semicolon.

I could check for all of these things:

```js
node.raws = Object.assign(
  node.raws.between ? { between: node.raws.between } : {},
  node.raws.semicolon ? { semicolon: true } : {},
  node.raws.important ? { important: node.raws.important } : {}
);
```

But then I am getting deeper into formatting. Which would you prefer?

**Comment by jonathantneal** [comment]
I’ve gone ahead and preserving things as documented above.
